name: Create Slideshow

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
      shell: bash

    - name: Create Slideshow
      run: |
        unzip -p '.github/workflows/to_mp4/images.zip' '*.jpg' | ffmpeg -framerate 1/10 -f image2pipe -i - -c:v libx264 -r 30 -pix_fmt yuv420p output.mp4
      shell: bash
      working-directory: $(System.DefaultWorkingDirectory)

    - name: Display Generated Files
      run: |
        ls -l
      shell: bash

    - name: Publish Slideshow Artifact
      uses: actions/upload-artifact@v2
      with:
        name: slideshow-artifact
        path: output.mp4
