name: Generate podcast audio

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  download_youtube_audio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip ffmpeg
        pip3 install yt-dlp

    - name: Run YouTube-DL command
      run: |
        yt-dlp --extract-audio --audio-format mp3 --postprocessor-args "-ss 00:32:22 -to 00:52:15" "https://www.youtube.com/watch?v=Ia4SGbnyc1E"

    - name: Prepare files
      run: |
        mkdir artifacts
        mv *.mp3 artifacts/

    - name: Upload MP3 files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: downloaded-audio
        path: |
          artifacts/
        if-no-files-found: fail # This line ensures the workflow fails if no files are found
