name: Generate Podcast

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  run_powershell:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell command
      run: |
        # Replace this line with your actual PowerShell command
        # For example, let's say you want to run a simple script
        pwsh -Command "Write-Host 'Hello, Generate Podcast!'"
